export enum ENV_VAR {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  SSL_ENABLED = 'SSL_ENABLED',

  // database connection
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_NAME = 'DB_NAME',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',

  // smtp
  SMTP_HOST = 'SMTP_HOST',
  SMTP_USER = 'SMTP_USER',
  SMTP_PASSWORD = 'SMTP_PASSWORD',
  SMTP_SERVICE = 'SMTP_SERVICE',
  SMTP_PORT = 'SMTP_PORT',

  // firebase config
  FIREBASE_PROJECT_ID = 'FIREBASE_PROJECT_ID',
  FIREBASE_CLIENT_EMAIL = 'FIREBASE_CLIENT_EMAIL',
  FIREBASE_PRIVATE_KEY = 'FIREBASE_PRIVATE_KEY',

  // url or links
  ADMIN_ACCOUNT_ACTIVATION_LINK = 'ADMIN_ACCOUNT_ACTIVATION_LINK',
  ADMIN_RESET_PASSWORD_LINK = 'ADMIN_RESET_PASSWORD_LINK',

  JWT_SECRET = 'JWT_SECRET',

  // password config
  PASSWORD_DEFAULT_LENGTH = 'PASSWORD_DEFAULT_LENGTH',
  PASSWORD_SALT_ROUNDS = 'PASSWORD_SALT_ROUNDS',
  PASSWORD_USE_SYMBOLS = 'PASSWORD_USE_SYMBOLS',
}
