export const users = [
  {
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    phone: '+1234567890',
    password: 'SecurePassword123',
  },
  {
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
    phone: '+1234567891',
    password: 'Password456!',
  },
  {
    firstName: 'Alice',
    lastName: 'Johnson',
    email: 'alice.johnson@example.com',
    phone: '+1234567892',
    password: 'Alice2024#',
  },
  {
    firstName: 'Robert',
    lastName: 'Brown',
    email: 'robert.brown@example.com',
    phone: '+1234567893',
    password: 'RbSecure!789',
  },
  {
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily.davis@example.com',
    phone: '+1234567894',
    password: 'EmilyPass22$',
  },
  {
    firstName: 'Michael',
    lastName: 'Williams',
    email: 'michael.williams@example.com',
    phone: '+1234567895',
    password: 'Mike@2023!',
  },
  {
    firstName: 'Sarah',
    lastName: 'Taylor',
    email: 'sarah.taylor@example.com',
    phone: '+1234567896',
    password: 'Taylor@Sarah1',
  },
  {
    firstName: 'David',
    lastName: 'Clark',
    email: 'david.clark@example.com',
    phone: '+1234567897',
    password: 'ClarkDavid!45',
  },
  {
    firstName: 'Laura',
    lastName: 'Martinez',
    email: 'laura.martinez@example.com',
    phone: '+1234567898',
    password: 'LauraMart1nez#',
  },
  {
    firstName: 'Daniel',
    lastName: 'Hernandez',
    email: 'daniel.hernandez@example.com',
    phone: '+1234567899',
    password: 'Daniel2023$%',
  },
  {
    firstName: 'Sophia',
    lastName: 'Lopez',
    email: 'sophia.lopez@example.com',
    phone: '+1234567800',
    password: 'Sophia_Lopez12',
  },
  {
    firstName: 'William',
    lastName: 'Young',
    email: 'william.young@example.com',
    phone: '+1234567801',
    password: 'WilliamYoung!88',
  },
  {
    firstName: 'Olivia',
    lastName: 'Walker',
    email: 'olivia.walker@example.com',
    phone: '+1234567802',
    password: 'OliviaW#2024',
  },
  {
    firstName: 'James',
    lastName: 'Scott',
    email: 'james.scott@example.com',
    phone: '+1234567803',
    password: 'JamesScott123',
  },
  {
    firstName: 'Mia',
    lastName: 'Green',
    email: 'mia.green@example.com',
    phone: '+1234567804',
    password: 'MiaGreen!45',
  },
  {
    firstName: 'Christopher',
    lastName: 'Hall',
    email: 'christopher.hall@example.com',
    phone: '+1234567805',
    password: 'ChrisHall@567',
  },
  {
    firstName: 'Amelia',
    lastName: 'Allen',
    email: 'amelia.allen@example.com',
    phone: '+1234567806',
    password: 'AmeliaA!990',
  },
  {
    firstName: 'Henry',
    lastName: 'Adams',
    email: 'henry.adams@example.com',
    phone: '+1234567807',
    password: 'Henry@Adams$1',
  },
  {
    firstName: 'Lily',
    lastName: 'Nelson',
    email: 'lily.nelson@example.com',
    phone: '+1234567808',
    password: 'LilyNelson99#',
  },
  {
    firstName: 'Andrew',
    lastName: 'Baker',
    email: 'andrew.baker@example.com',
    phone: '+1234567809',
    password: 'AndrewBaker!78',
  },
];
