import { type FC } from 'react';
import { Html } from '@react-email/components';

interface Props {
  firstName: string;
  email: string;
  activationLink: string;
  password: string;
}

/**
 * Email template component for notifying users about a new account creation.
 *
 * @component
 * @param {Props} props - The component props.
 * @param {string} props.firstName - The first name of the recipient.
 * @param {string} props.email - The email address of the recipient.
 * @param {string} props.activationLink - The link to activate the account.
 * @param {string} props.password - The  autogenerated password.
 * @returns {JSX.Element} The email template.
 */
export const NewAccount: FC<Props> = (props) => {
  const { firstName, activationLink, password } = props;
  return (
    <Html style={{ display: 'flex', justifyContent: 'center' }}>
      <h1>🎉 Bienvenido a EstbelSoft!</h1>
      <h4 style={{ fontSize: '24px' }}>hola {firstName},</h4>
      <p style={{ fontSize: '24px' }}>
        Tu cuenta ha sido creada exitosamente. Click en el button de abajo para
        cambiar tu contraseña
      </p>
      <p style={{ fontSize: '24px' }}>
        <a href={activationLink} target="_blank" rel="noreferrer">
          {activationLink}
        </a>
      </p>
      <p>
        Puedes entrar en tu cuenta usando esta contraseña provisional{' '}
        <span
          style={{
            background: '#F6F4F0',
            padding: '5px',
            borderRadius: '10px',
            color: '#2E5077',
          }}
        >
          {password}
        </span>
      </p>
      <p style={{ fontSize: '24px' }}>Bendiciones,</p>
      <p style={{ fontSize: '24px' }}> Estbel team</p>
    </Html>
  );
};
