import { Html } from '@react-email/components';

interface Props {
  firstName: string;
  email: string;
  activationLink: string;
  password: string;
}

/**
 * Email template component for notifying users about a new account creation.
 * @component
 * @param {Props} props - The component props.
 * @param {string} props.firstName - The first name of the recipient.
 * @param {string} props.email - The email address of the recipient.
 * @param {string} props.activationLink - The link to activate the account.
 * @param {string} props.password - The  autogenerated password.
 * @returns {JSX.Element} The email template.
 */
export const NewAccount = (props: Props) => {
  const { firstName, activationLink, password } = props;
  return (
    <Html>
      <h1>🎉 Bienvenido a EstbelSoft!</h1>
      <p style={{ fontSize: '16px' }}>hola {firstName},</p>
      <p style={{ fontSize: '16px' }}>
        Tu cuenta ha sido creada exitosamente. Click en el enlace de abajo para
        cambiar tu contraseña
      </p>
      <p style={{ fontSize: '16px' }}>
        <a href={activationLink} target="_blank" rel="noreferrer">
          Enlace para cambiar crear nueva contraseña o activar cuenta
        </a>
      </p>
      <p style={{ fontSize: '16px' }}>
        Puedes entrar en tu cuenta usando esta contraseña provisional{' '}
      </p>
      <span
        style={{
          fontSize: '22px',
          background: '#F6F4F0',
          padding: '5px',
          borderRadius: '10px',
          color: '#2E5077',
        }}
      >
        {password}
      </span>
      <p style={{ fontSize: '16px' }}>Bendiciones,</p>
      <p style={{ fontSize: '16px', fontStyle: 'italic' }}> Estbel team</p>
    </Html>
  );
};
