name: estbel-testing

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: write

jobs:
  build:
    name: test-code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Run ESLint
        run: npm run lint -- --fix

      - name: Run Prettier
        run: npx prettier --write .

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_ENV
          else
            echo "has_changes=true" >> $GITHUB_ENV
          fi

      - name: Get list of changed files
        id: changed_files
        run: |
          files=$(git diff --name-only)
          echo "::set-output name=files::$files"

      - name: Commit changes using Verified Commit action
        if: env.has_changes == 'true' && github.event_name == 'push'
        uses: swinton/commit@v2.x
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: 'fix: auto-format code with Prettier and ESLint'
          ref: refs/heads/develop
          files: ${{ steps.changed_files.outputs.files }}
